preset: strict
severity: error

rules:
  metaTags:
    title-exists:
      enabled: true
      severity: error
    title-length-valid:
      enabled: true
      severity: error
    meta-description-exists:
      enabled: true
      severity: error
    meta-description-length-valid:
      enabled: true
      severity: error
    viewport-meta-exists:
      enabled: true
      severity: error
    canonical-url-exists:
      enabled: true
      severity: error
    og-title-exists:
      enabled: true
      severity: error
    og-description-exists:
      enabled: true
      severity: error
    og-image-exists:
      enabled: true
      severity: error

  headings:
    h1-exists:
      enabled: true
      severity: error
    h1-count-valid:
      enabled: true
      severity: error
    heading-hierarchy-valid:
      enabled: true
      severity: error

  images:
    images-have-alt:
      enabled: true
      severity: error
    alt-text-quality:
      enabled: true
      severity: warning

  security:
    https-enabled:
      enabled: true
      severity: error
    mixed-content-check:
      enabled: true
      severity: error

  accessibility:
    enabled: true
    severity: error

  performance:
    enabled: true
    severity: warning

  structuredData:
    enabled: true
    severity: error

  socialMedia:
    enabled: true
    severity: error

  coreWebVitals:
    enabled: true
    severity: error

  mobileUX:
    enabled: true
    severity: error
