# Custom configuration example
# Mix and match rules from different presets

preset: advanced
severity: warning

rules:
  # Enable only specific checker groups
  metaTags: true
  headings: true
  images: true
  performance: true
  security: true
  accessibility: true

  # Disable advanced checkers
  structuredData: false
  socialMedia: false
  spamDetection: false
  pageQuality: false
  advancedImages: false
  multimedia: false
  coreWebVitals: false
  analytics: false
  mobileUX: false
  schemaValidation: false
  resourceOptimization: false
  legalCompliance: false
  ecommerce: false
  internationalization: false

  # Fine-tune specific rules
  metaTags:
    title-exists:
      enabled: true
      severity: error
    title-length-valid:
      enabled: true
      severity: warning
      options:
        minLength: 30
        maxLength: 60

  security:
    https-enabled:
      enabled: true
      severity: error
